### ISSUE TITLE
gelf-formatter induces logging error in django when uncaptured exception is raised

### ISSUE THREAD

**Issue by 0mbi** [joaodrp/gelf-formatter#16]
**Problem:**
Despite the fact that exception should be captured, when 
doing so in a django request handler, gelf-formatter produces
a logging error caused by
> TypeError: Object of type WSGIRequest is not JSON serializable

**Solution:**
This can be fixed by converting value to string for non json serialzable objects:
`log_record[_prefix(key)] = str(value)`

**Comment by joaodrp** [comment]
Fixed with #18
